### ISSUE TITLE
DB

### ISSUE THREAD

**Issue by yelimpark** [Rory0304/movienote#5]
원래 계획은 heroku에서 제공하는 db를 사용하는 것이였지만, 유료서비스인 관계로 대안을 몇개 생각해보았습니다.

- AWS 등 다른 서비스를 이용하여 db 서버를 구축한다.
- 프로젝트용이고, db가 간단한 구조이므로 그냥 txt 파일을 이용한다

더 나은 아이디어 있는 분...

**Comment by yelimpark** [comment]
우선은 샘플이라도 넣어놨습니다 ㅜㅜ

**Comment by Rory0304** [comment]
헤로쿠 무료 플랜은 일정 db 용량 제한이 있어서 넘어가면 서비스 이용 못하는 형태고, 아마존은 첫회원 1년 무료임. 근데 난 1년 지나서 과금됨.
