### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by sersue** [Rory0304/movienote#6]
Title이 버튼으로 만들어져 있는데, 눌렀을 때의 기능이 아직 추가되지 않은 것 같습니다.
Title 버튼을 눌렀을 때 리스트가 새로 생성되거나, 전체 페이지의 새로고침 기능이 추가되었으면 좋겠습니다!

**Comment by Rory0304** [comment]
title?? 그 영화 타이틀 말하는건지? 아니면 헤더 부분 title 말하는건가!? 영화 타이틀 누르면 디테일 페이지로 이동은 됩니다!

**Comment by sersue** [comment]
자세하게 안썼네용.. 언급한 title은 헤더부분 title 입니당!
